-- MySQL Script generated by MySQL Workbench
-- 2018年07月10日 星期二 16时38分07秒
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS, UNIQUE_CHECKS = 0;
SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS = 0;
SET @OLD_SQL_MODE = @@SQL_MODE, SQL_MODE = 'TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema distributed_demo
-- -----------------------------------------------------
-- 分布式demo-schema

-- -----------------------------------------------------
-- Schema distributed_demo
--
-- 分布式demo-schema
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `distributed_demo`
  DEFAULT CHARACTER SET utf8;
USE `distributed_demo`;

-- -----------------------------------------------------
-- Table `distributed_demo`.`tb_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `distributed_demo`.`tb_user`;

CREATE TABLE IF NOT EXISTS `distributed_demo`.`tb_user` (
  `id`          BIGINT(20)  NOT NULL AUTO_INCREMENT,
  `username`    VARCHAR(30) NOT NULL,
  `password`    VARCHAR(45) NOT NULL,
  `create_time` TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted`     TINYINT     NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
)
  ENGINE = InnoDB;


SET SQL_MODE = @OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;
