server:
  port: 8202
spring:
  application:
    name: business-consumer

# dubbo config
dubbo:
  scan:
    base-packages: per.wilson.distributed.controller
  application:
    name: business-consumer
    id: business-consumer
  protocol:
    id: business-consumer
    name: business-consumer
    port: 10002
  registry:
      address: multicast://224.5.6.7:1234
      check: false
  consumer:
    check: false
    timeout: 300

# eureka config
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    client:
        enabled: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
