server:
  port: 8081
spring:
  application:
    name: user-provider
  profiles:
    include: jdbc
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        health-check-path: ${managemant.contextPath}/health
      config:
        enabled: true

dubbo:
  scan:
    base-packages: per.wilson.distributed.service
  application:
    name: provider
    id: provider
  protocol:
    id: dubbo
    name: dubbo
    port: 33333
  registry:
    address: multicast://224.5.6.7:1234
    check: false

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    client:
        enabled: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/


redis:
  max-idle: 10
  min-idle: 5