server:
  port: 8081
spring:
  application:
    name: user-provider
dubbo:
  scan:
    base-packages: per.wilson.distributed.service
  application:
    name: provider
    id: provider
  protocol:
    id: dubbo
    name: dubbo
    port: 33333
  registry:
    address: multicast://224.5.6.7:1234
    check: false

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    client:
        enabled: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
