server:
  port: 8081
spring:
  application:
    name: user-provider
  profiles:
    include: jdbc,redis,dubbo
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        health-check-path: /actuator/health
        service-name: user-provider
        enabled: true
      enabled: true

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    enabled: true

